### ISSUE TITLE
Unable to install using install_github

### ISSUE THREAD

**Issue by chilger** [ramnathv/slidifyLibraries#12]
> install_github("slidifyLibraries", "ramnathv")
> Installing github repo(s) slidifyLibraries/master from ramnathv
> Installing slidifyLibraries.zip from https://github.com/ramnathv/slidifyLibraries/archive/master.zip
> Installing slidifyLibraries
> pdflatex not found. Not building PDF vignettes.
> "C:/PROGRA~1/R/R-215~1.1/bin/x64/R" --vanilla CMD build  \
>   "C:\Users\chilger\AppData\Local\Temp\RtmpEX6rrK\slidifyLibraries-master"  \
>   --no-manual --no-resave-data --no-vignettes 
- checking for file 'C:\Users\chilger\AppData\Local\Temp\RtmpEX6rrK\slidifyLibraries-master/DESCRIPTION' ... OK
- preparing 'slidifyLibraries':
- checking DESCRIPTION meta-information ... OK
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- building 'slidifyLibraries_0.1.tar.gz'
  Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9,  :
  storing paths of more than 100 bytes is not portable:
  'slidifyLibraries/inst/libraries/frameworks/landslide/themes/machinalis/fonts/OFLGoudyStMTT-Italic.ttf'
  Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9,  :
  storing paths of more than 100 bytes is not portable:
  'slidifyLibraries/inst/libraries/frameworks/showoff/css/theme/images/ui-bg_diagonals-small_100_f0efea_40x40.png'

(snip)

Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9,  :
  storing paths of more than 100 bytes is not portable:
  'slidifyLibraries/inst/libraries/widgets/mathjax/jax/output/SVG/fonts/TeX/Typewriter/Regular/CombDiacritMarks.js'

"C:/PROGRA~1/R/R-215~1.1/bin/x64/R" --vanilla CMD INSTALL  \
  "C:\Users\chilger\AppData\Local\Temp\RtmpEX6rrK/slidifyLibraries_0.1.tar.gz"  \
  --library="C:/Users/chilger/Documents/R/win-library/2.15"  \
  --with-keep.source 

Warning in max(which(block[1:100] > 0)) :
  no non-missing arguments to max; returning -Inf
Warning in rawToChar(block[seq_len(ns)]) : NAs introduced by coercion
Error in seq_len(ns) : argument must be coercible to non-negative integer
Error: Command failed (1)

**Comment by ramnathv** [comment]
Do you have the latest versions of R (2.15.2) and `devtools` installed? Can you print your `sessionInfo()`?

**Comment by chilger** [comment]
Thanks for the quick response.  Turns out I was running 2.15.1.  After upgrading to 2.15.2 the error has gone away and I was able to install the package.

If you're still interested in the session info from the 2.15.1 issue:

> sessionInfo()
> R version 2.15.1 (2012-06-22)
> Platform: x86_64-pc-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C  
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.0

loaded via a namespace (and not attached):
[1] digest_0.6.1    evaluate_0.4.3  httr_0.2        memoise_0.1  
[5] parallel_2.15.1 RCurl_1.95-3    stringr_0.6.2   tools_2.15.1  
[9] whisker_0.1

**Comment by ramnathv** [comment]
Great. I believe this has something to do with `install_github` and `devtools`. Anycase, good to know that you were able to resolve the issue.

**Comment by mol68** [comment]
I am trying to install slidify and I had the following error (working with RStudio Version 0.98.501 and Windows XP):

> install_github("slidifyLibraries", "ramnathv")
> Installing github repo slidifyLibraries/master from ramnathv
> Downloading master.zip from https://github.com/ramnathv/slidifyLibraries/archive/master.zip
> Installing package from C:\DOCUME~1\ADMINI~1\CONFIG~1\Temp\RtmpuKAivx/master.zip
> Installing slidifyLibraries
> "C:/ARCHIV~1/R/R-30~1.3/bin/i386/R" --vanilla CMD INSTALL "C:\Documents and  \
>   Settings\Administrador\Configuración  \
>   local\Temp\RtmpuKAivx\devtoolsf6448fc3edd\slidifyLibraries-master" --library="C:/Archivos de  \
>   programa/R/R-3.0.3/library" --install-tests 

Warning: invalid package 'C:\Documents and Settings\Administrador\Configuración local\Temp\RtmpuKAivx\devtoolsf6448fc3edd\slidifyLibraries-master'
Error: ERROR: no packages specified
Error: Command failed (1)

Thanks
